### ISSUE TITLE
Unable to begin pairing process

### ISSUE THREAD

**Issue by LividJava** [patri9ck/a2ln-app#21]
Hi there,
I'm attempting to setup this application on my LG Stylo 4 (LM-Q710).

I have the server setup and it's responding with a public key and pairing server.

However when entering this into the application (F-Droid version as I cannot find the Google Play version Link is broken) it doesn't initiate any sort of pairing request. Is there anywhere I should start looking for troubleshooting

Thanks in Advance.

**Comment by patri9ck** [comment]
Hey, thanks for your issue. Did you follow the guide at https://www.patri9ck.dev/a2ln/pairing.html? Are both of your devices in the same LAN?

**Comment by LividJava** [comment]
Yes I've followed the guide exactly as is. Devices are on the same LAN. I'm not using a port that requires root.

I will note, when I go to add a device, My screen looks slightly different than the screenshots.

![image](https://user-images.githubusercontent.com/7604544/178612540-6301be76-8b7e-441f-b39c-2e54468e5e32.png)

**Comment by LividJava** [comment]
Alright, Yeah F-Droid only has version 1.1.1 from what I can tell. Do you have build instructions so I can compile the app myself in the mean time?

**Comment by patri9ck** [comment]
I guess the easiest way would be to install Android Studio, import the project, enable developer mode on your phone, plug it with a USB cable into your PC and install the app there. In the future I will provide APKs here on GitHub.

**Comment by LividJava** [comment]
Confirmed working in ver 1.2.0

**Comment by WeebNetsu** [comment]
This issue seems to potentially be back, I tried connecting via the QR code (Using Xiaomi Redmi 9T and Linux Mint 21), but nothing happened on either end, the pairing just fails (I am on the same network). The logs just says:

```
Trying to pair with <my address>:35397
Failed to send own IP and public key to <my address>:35397
```

**Comment by patri9ck** [comment]
Strange. I don't remember actually fixing something specific to make it work. Does a simple ping, for example from your computer to your phone, work?

**Comment by WeebNetsu** [comment]
Yes, pinging seems to go through without any issues

**Comment by patri9ck** [comment]
Does a firewall maybe block the pairing port?

**Comment by WeebNetsu** [comment]
Yes! On the head, disabling my firewall on the port made it work instantly, thank you for the help!
