### ISSUE TITLE
Include app name in notification.

### ISSUE THREAD

**Issue by sophronesis** [patri9ck/a2ln-app#26]
My main use-case of this app is that I'm making local pipeline that would parse notifications from apps and include it as watcher to [ActivityWatch](https://github.com/ActivityWatch/activitywatch). Also would be great to filter notifications from my banking app for easy transactions tracking.

**Comment by patri9ck** [comment]
Thank you for the issue. I will add a way to toggle it and also a way to specify the format of the title.
