### ISSUE TITLE
Run script on notification recieved

### ISSUE THREAD

**Issue by sophronesis** [patri9ck/a2ln-app#27]
Title is quiet descriptive, I think.

**Comment by patri9ck** [comment]
Thanks for the issue. I guess the easiest way to implement this would be a command line option where you can specify a shell command with two placeholders for the notification's title and body that gets executed everytime there is a notification.

**Comment by patri9ck** [comment]
Just for clarification, it's about the server running a script on the computer, not the app running a script on the phone, right?

**Comment by sophronesis** [comment]
> Just for clarification, it's about the server running a script on the computer, not the app running a script on the phone, right?

Yep, I have digital ocean server, and want it to run a2ln server with script, that will send it to telegram and to ActivityWatch.

**Comment by patri9ck** [comment]
I created a new issue for the correct project: https://github.com/patri9ck/a2ln-server/issues/10
