### ISSUE TITLE
How to get notifications from the Work Profile?

### ISSUE THREAD

**Issue by vbooka1** [patri9ck/a2ln-app#31]
I want to read notifications from the apps installed into the Work Profile, unfortunately I couldn't find a way to do that.

Android permissions system does not allow applications which are installed into a Work Profile to read any notifications at all, so I could not install A2LN into the Work Profile (well, technically I could, but it will not get any notifications).

And applications which are installed into the main profile do not have access to notifications from apps installed into a Work Profile. So if I install A2LN into the main profile (as you would install any other app) it will not be able to read notifications from the apps from the Work Profile.

Is there any workaround for this?

**Comment by patri9ck** [comment]
The last few days, I looked for a solution but didn't found one, unfortunately. At the moment, this cannot be fixed.
