### ISSUE TITLE
Allow enabling/disabling individual notification channels per app

### ISSUE THREAD

**Issue by DanielJutz** [patri9ck/a2ln-app#35]
# Is your feature request related to a problem?
I would like to disable the persistent notification for K9 mail which is in a separate channel, but not other notifications from K9 mail.

# Description
Provide a checkbox for each notification channel per app to enable disable sending those notifications.

**Comment by patri9ck** [comment]
After a quick research, I don't think this is possible. For this to work, the app would need to know the channel IDs K-9 mail uses before any notification is ever posted which does not work.
