### ISSUE TITLE
Allow specifying servers with domain name

### ISSUE THREAD

**Issue by DanielJutz** [patri9ck/a2ln-app#36]
# Is your feature request related to a problem?
My fritzbox router resolves `hostname.fritz.box` to my device's ip. this is more convenient to remember and removes the need for a static ip. Currently only numerical characters are allowed when pairing to a new server.

# Description
I'd like to be able to enter non numerical characters when pairing to a new server.

Thanks for the a2ln project!

**Comment by patri9ck** [comment]
It's something I already took a look at but as far as I know, it is something that has to be done at your DNS server which will redirect the from the domain to the corresponding IP. At least I do not know any other way.

**Comment by patri9ck** [comment]
I will implement it, thank you!

**Comment by rdlmda** [comment]
Doesn't seem to work for me, how can I proceed?
