### ISSUE TITLE
Failure To Connect

### ISSUE THREAD

**Issue by Ao1Pointblank** [patri9ck/a2ln-app#37]
# Description
App fails to send own IP and public key to `server ip` `random port`

# Reproduction
running a2ln server with no parameters, no firewall, on same wifi network, on latest version from pip, v1.1.10
app version 1.2.7

# Screenshots
![Screenshot_20230412-172406 resized](https://user-images.githubusercontent.com/88149675/231590070-67951a8b-b071-454d-b9c1-6f27b0889ddc.png)
![Screenshot_20230412-172416 resized](https://user-images.githubusercontent.com/88149675/231590081-fddca512-e3d4-46e1-ac96-d0c0466f1d8a.png)

# Smartphone
 - Device: Pixel 5
 - Android version: Android 13  / GrapheneOS

**Comment by patri9ck** [comment]
Can you ping your phone? 
```
$ ping 192.168.0.50
```

**Comment by patri9ck** [comment]
Can you show the output when you run `$ a2ln`?

**Comment by Ao1Pointblank** [comment]
![image](https://user-images.githubusercontent.com/88149675/231595696-7de1194d-fc14-4249-84d9-7829b28da5c9.png)

**Comment by patri9ck** [comment]
Everything looks fine? It used to work, right? Do you remember changing anything in your network configuration or something similar?

**Comment by Ao1Pointblank** [comment]
no intentional changes to my network, but the IPs of my devices sometimes change when the router has to be reset after a power outage.

**Comment by Ao1Pointblank** [comment]
the request just never comes through to the server.
are the public keys supposed to not match?

**Comment by Ao1Pointblank** [comment]
wait, i will try deleting all my configs for the server

**Comment by patri9ck** [comment]
Yes, they do not match. The server as well as the client (your phone) have their own public key.

**Comment by Ao1Pointblank** [comment]
i'll try with a different phone

**Comment by Ao1Pointblank** [comment]
nevermind, it isn't compatible with my old phone (android 8)

**Comment by Ao1Pointblank** [comment]
um i think i figured it out. i had installed portmaster, another firewall tool recently. i thought it was inactive. no system tray icon or processes with that name running. it was still blocking things somehow as a firewall. sorry to waste your time.

**Comment by patri9ck** [comment]
No problem, you didn't waste my time! Glad to hear that you found the issue!
