### ISSUE TITLE
Disable showing persistent notifications

### ISSUE THREAD

**Issue by xrtxn** [patri9ck/a2ln-app#38]
# Description
I would like to disable a2ln to show persistent notifications (like download notifications and such) which spams the notifications.

**Comment by patri9ck** [comment]
This can be done by disabling the app causing the notification in the "Apps" tab.

**Comment by xrtxn** [comment]
Not really, if I disable the app, I will not get any notification. I still would like to receive the normal notifications.

**Comment by patri9ck** [comment]
I see. How about this: If two consecutive notification are at least to x % equal, the notification will be blocked for the next y minutes. Would this work for you? X and y can be set by the user.

**Comment by patri9ck** [comment]
Implemented, see #39
