### ISSUE TITLE
Pairing always fails

### ISSUE THREAD

**Issue by pierfu** [patri9ck/a2ln-app#41]
# Description
Pairing always fails to succeed

# Reproduction
- PC : run a2ln, without firewall at all
- PC : run a2ln pair
- phone : open a2ln app, touch add server, scan QRCode
- PC : answer Yes pairing -> always fails
 
# Screenshots
Log from a2ln app screenshot
![a2ln-app log](https://github.com/patri9ck/a2ln-app/assets/1388024/2347393a-d124-4792-959e-7a31b618b8d1)

# Smartphone
- Device: Sony Xperia
- Android version: LineageOS 19.1

**Comment by pierfu** [comment]
I can see packet exchange with tcpdump, in/out.

**Comment by patri9ck** [comment]
Right now, pairing fails because of an yet unreleased version of the app. At the end of the coming week, I will have a computer again to publish the update. To fix the issue, you can use the latest release of the server which works with the latest release of the app.

**Comment by pierfu** [comment]
Let le now after you updated the app. I have both last versions of server (1.1.13) and app (1.3.2) but problem remains.

**Comment by patri9ck** [comment]
Pairing works now with version [1.1.14](https://github.com/patri9ck/a2ln-server/releases/tag/1.1.14) of the server and version [1.3.3](https://github.com/patri9ck/a2ln-app/releases/tag/1.3.3) of the app, though it may take some days until the app is updated on Google Play and F-Droid.

Does the problem persist?

**Comment by pierfu** [comment]
Yeah pairing works now, tks !
