### ISSUE TITLE
I can't grant notifications access

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [patri9ck/a2ln-app#42]
# Ask your question, whatever it may be
I installed the app with fdroid and I can't grant notifications. It said for your safety you can't grant.

Android 13

**Comment by patri9ck** [comment]
Which device do you use?

That seems like a issue I cannot do anything about.

**Comment by jojojojojoj5564656465465** [comment]
I am using a realme oppo and endeavour osSent from Android deviceLe 18 déc. 2023 22:23, Patrick ***@***.***> a écrit :
Which device do you use?
That seems like a issue I cannot do anything about.
