### ISSUE TITLE
Update Received messages in linux

### ISSUE THREAD

**Issue by SychoAN** [patri9ck/a2ln-app#43]
# Description
some apps on my phone send a notification and changes it in seconds
like whatsapp for example
it sends
"Checking for messages..."
then it changes the same notification not creating another one
so in linux I only get checking for messages

another thing
if I got a telegram notification then I opened it on the web or desktop app
the notifications gets removed in phone after seeing the sent message
but on linux it's not...

that's what I am saying
your app should update (reload) the current notifications every minute or something
so if a notification got removed or Edited it should be edited on linux also

# Reproduction
Just use whatsapp and you will see the "Checking for messages..." notification and it will not be edited to the received message

# Smartphone
- Device:infinix hot 5
- Android version: 8.1

**Comment by SychoAN** [comment]
Sorry I know I didn't make it clear but here's an example with messages app [sms]
2 screenshots of what I get on linux and android

![image](https://github.com/patri9ck/a2ln-app/assets/61439740/e04ade91-f9d0-45bf-bc10-1b307c9e3474)

![image](https://github.com/patri9ck/a2ln-app/assets/61439740/9d283e48-5e95-4105-b4f1-26f8b168be7d)

**Comment by patri9ck** [comment]
Strange, I know those messages from WhatsApp, but for me, they worked fine. You can try to set the delay in the settings to the lowest minimum, 1 second.

**Comment by patri9ck** [comment]
Closing as of inactivity.
