### ISSUE TITLE
Add command examples in documentation  ?

### ISSUE THREAD

**Issue by pierfu** [patri9ck/a2ln-app#44]
Hi,
I cannot figure out what kind of "command" can be used.
I tried  this: 
--command "notify-send {app}:{title} {body}"
but doesn't work
Tried the same run by shell script, failed too.
Tkx.

**Comment by patri9ck** [comment]
You quoted your command incorrectly.  This works for me:
```
a2ln --command 'notify-send "{app}:{title}" "{body}"'
```
