### ISSUE TITLE
Interested in Material 3 adoption?

### ISSUE THREAD

**Issue by cyb3rko** [patri9ck/a2ln-app#45]
Moin Patrick,  
first of all thanks for the app and the a2ln service, I've been using it for a few months now.

Are you interested in implementing Material 3 as a design update for your app?  
I could do that for a2ln as one way to support this project.

**Comment by patri9ck** [comment]
Hey, that is something I also thought about but I didn't know where to get started. I would really like the app to use Material 3.

**Comment by patri9ck** [comment]
Closed, see #46
