### ISSUE TITLE
Way to accept Notification Actions, like: mark as read, or dismiss etc.

### ISSUE THREAD

**Issue by sanjeevprasad** [patri9ck/a2ln-app#49]
It is nice to have an list of Notification Action options also available, and somehow send the command back to the app. and App auto accepts or rejects or "Mark as read". the notification.  I don't know if it is even possible through android SDK.

Basically what I am looking for is to remotely select an option that notification is showing on my phone, without unlocking the phone.

Is this something that we can implement?

In the end, Thanks for this app, and a2ln-server.

**Comment by patri9ck** [comment]
Hey, as far as I know, this is not possible for security reasons unfortunately. Nice to hear that you like the app!
