### ISSUE TITLE
Enhance UI

### ISSUE THREAD

**Issue by Domi04151309** [patri9ck/a2ln-app#7]
Currently the UI is very basic. I like the idea of the app and would like to create an improved UI in the future.

**Comment by patri9ck** [comment]
To be honest I am not good at designing UIs so a new one would probably be great! Feel free to create a PR whenever you want. Also, I am happy to hear that you like the app.

**Comment by Domi04151309** [comment]
If you want you can check out the [`main-activity` branch](https://github.com/Domi04151309/a2ln-app/tree/main-activity) of my fork to see a new layout concept I did.

**Comment by patri9ck** [comment]
See #12
